# .github/workflows/build-windows.yml

name: Build Windows App

# 1) Dá permissão de escrita em conteúdo para o GITHUB_TOKEN
permissions:
  contents: write

on:
  push:
    branches:
      - master    # ou sua branch principal

jobs:
  build-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: pwsh

    steps:
      # 2) Faz checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 3) Configura o Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 4) Instala dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PySide6 pillow opencv-python

      # 5) Empacota o EXE com PyInstaller
      - name: Build standalone EXE (sem ícone)
        run: |
          pyinstaller `
            --noconfirm `
            --clean `
            --onefile `
            --windowed `
            --add-data "models;models" `
            photo_importer_app.py

      # 6) Compacta num ZIP
      - name: Compress EXE to ZIP
        run: |
          Compress-Archive -Path dist\photo_importer_app.exe -DestinationPath PhotoImporter-Windows.zip

      # 7) Cria a GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          # tag e nome baseado no número da execução
          tag_name: v${{ github.run_number }}
          release_name: v${{ github.run_number }}
          body: Build automática via GitHub Actions para Windows

      # 8) Carrega o ZIP como asset
      - name: Upload ZIP as release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: PhotoImporter-Windows.zip
          asset_name: PhotoImporter-Windows.zip
          asset_content_type: application/zip
