# .github/workflows/build-windows.yml

name: Build Windows App

on:
  push:
    branches:
      - master    # ou sua branch principal

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PySide6 pillow opencv-python

      - name: Build standalone EXE (sem ícone)
        shell: pwsh
        run: |
          pyinstaller `
            --noconfirm `
            --clean `
            --onefile `
            --windowed `
            --add-data "models;models" `
            photo_importer_app.py

      - name: Compress EXE to ZIP
        shell: pwsh
        run: |
          Compress-Archive -Path dist\photo_importer_app.exe -DestinationPath PhotoImporter-Windows.zip

      - name: Publish GitHub Release with asset
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extrai OWNER e REPO
          $parts = "${{ github.repository }}" -split '/'
          $owner = $parts[0]
          $repo  = $parts[1]
          $tag   = "v${{ github.run_number }}"

          Write-Host "Creating release $tag..."
          $body = @{ tag_name = $tag; name = $tag; body = "Build automática via GitHub Actions para Windows" } | ConvertTo-Json
          $release = Invoke-RestMethod -Method Post `
            -Uri "https://api.github.com/repos/$owner/$repo/releases" `
            -Headers @{ Authorization = "Bearer $env:GITHUB_TOKEN"; "Content-Type" = "application/json" } `
            -Body $body

          $uploadUrl = $release.upload_url -split '\{' | Select-Object -First 1

          Write-Host "Uploading PhotoImporter-Windows.zip..."
          Invoke-RestMethod -Method Post `
            -Uri "$uploadUrl?name=PhotoImporter-Windows.zip" `
            -Headers @{ Authorization = "Bearer $env:GITHUB_TOKEN"; "Content-Type" = "application/zip" } `
            -InFile "PhotoImporter-Windows.zip"

          Write-Host "Release $tag criado com sucesso."
