name: Build Windows App

on:
  push:
    branches:
      - master    # ou sua branch principal
jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PySide6 pillow opencv-python

      - name: Build standalone EXE
        run: |
          pyinstaller ^
            --noconfirm ^
            --clean ^
            --onefile ^
            --windowed ^
            --add-data "models;models" ^
            --icon icon.ico ^
            photo_importer_app.py

      - name: Package into ZIP
        run: |
          powershell -Command "Compress-Archive -Path dist\photo_importer_app.exe -DestinationPath PhotoImporter-Windows.zip"

      - name: Verify GitHub CLI
        run: gh --version

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # define tag baseado no número de execução
          TAG="v${{ github.run_number }}"
          echo "Criando release $TAG..."
          gh release create "$TAG" \
            PhotoImporter-Windows.zip \
            --title "PhotoImporter Windows build #${{ github.run_number }}" \
            --notes "Build automática via GitHub Actions para Windows"
