name: Build macOS App

on:
  push:
    branches: [ master ]       # ou 'master' se for o seu caso

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install py2app PySide6 pillow opencv-python

      - name: Build .app
        run: python setup.py py2app

      - name: Upload macOS App artifact
        uses: actions/upload-artifact@v2
        with:
          name: PhotoImporter-macOS
          path: dist/photo_importer_app.app
