# .github/workflows/build-windows.yml

name: Build Windows App

on:
  push:
    branches:
      - master    # ou sua branch principal

permissions:
  contents: write   # permite criar releases e fazer upload de assets

jobs:
  build-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PySide6 pillow opencv-python

      - name: Build standalone EXE (sem ícone)
        run: |
          pyinstaller `
            --noconfirm `
            --clean `
            --onefile `
            --windowed `
            --add-data "models;models" `
            photo_importer_app.py

      - name: Compress EXE to ZIP
        run: |
          Compress-Archive -Path dist\photo_importer_app.exe -DestinationPath PhotoImporter-Windows.zip

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: v${{ github.run_number }}
          body: Build automática via GitHub Actions para Windows
          draft: false
          prerelease: false

      - name: Upload ZIP as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: PhotoImporter-Windows.zip
          asset_name: PhotoImporter-Windows.zip
          asset_content_type: application/zip
