name: Build macOS App

# dispara em push na branch main (ou altere para a sua branch)
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-macos:
    # utiliza o runner macOS mais recente
    runs-on: macos-latest

    steps:
      # 1. faz checkout do seu código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. configura a versão de Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. instala dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py2app PySide6 pillow opencv-python

      # 4. gera o bundle .app
      #    espera existir um setup.py configurado com py2app
      - name: Build macOS .app
        run: python setup.py py2app

      # 5. faz upload do .app gerado como artefato
      - name: Upload macOS App artifact
        uses: actions/upload-artifact@v3
        with:
          name: PhotoImporter-macOS
          path: dist/photo_importer_app.app
