# .github/workflows/build-macos.yml

name: Build macOS App

on:
  push:
    branches:
      - master    # ajuste para 'master' se for o seu caso

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py2app PySide6 pillow opencv-python

      - name: Build .app bundle
        run: python setup.py py2app

      - name: Compress .app to ZIP
        run: ditto -c -k --keepParent dist/photo_importer_app.app PhotoImporter-macOS.zip

      - name: Install GitHub CLI (gh) via Homebrew
        run: |
          if ! command -v gh >/dev/null; then
            brew install gh
          fi

      - name: Verify gh version
        run: gh --version

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${{ github.run_number }}" \
            PhotoImporter-macOS.zip \
            --title "PhotoImporter macOS build #${{ github.run_number }}" \
            --notes "Build automática via GitHub Actions"
